apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello
  annotations:
    backstage.io/kubernetes-id: hello
    prometheus.io/rule: sum by (instance) (node_cpu_seconds_total)
    prometheus.io/alert: all
spec:
  type: service
  lifecycle: experimental
  owner: group:default/developer
