apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello
  annotations:
    backstage.io/kubernetes-id: hello
    prometheus.io/rule: ''
spec:
  type: service
  lifecycle: experimental
  owner: group:default/devops
