variables:
  Azure_serviceConnection_des: xxxxxxxxxxxxxxx
  aks_admin_group_object_ids: xxxxxxxxxxxxxxx
  aks_default_node_pool_max_count: xxxxxxxxxxxxxxx
  aks_default_node_pool_min_count: xxxxxxxxxxxxxxx
  aks_default_node_pool_vm_size: xxxxxxxxxxxxxxx
  aks_prometheus_enabled: xxxxxxxxxxxxxxx
  aks_workloads_node_pool_max_count: xxxxxxxxxxxxxxx
  aks_workloads_node_pool_min_count: xxxxxxxxxxxxxxx
  aks_workloads_node_pool_node_taints: xxxxxxxxxxxxxxx
  aks_workloads_node_pool_spot_enabled: xxxxxxxxxxxxxxx
  aks_workloads_node_pool_vm_size: xxxxxxxxxxxxxxx
  apim_autoscale_decrease: xxxxxxxxxxxxxxx
  apim_autoscale_default_capacity: xxxxxxxxxxxxxxx
  apim_autoscale_default_maximum: xxxxxxxxxxxxxxx
  apim_autoscale_default_minimum: xxxxxxxxxxxxxxx
  apim_autoscale_increas: xxxxxxxxxxxxxxx
  apim_sku_capacity: xxxxxxxxxxxxxxx
  apim_sku_name: xxxxxxxxxxxxxxx
  enabled_aks: xxxxxxxxxxxxxxx
  enabled_apim: xxxxxxxxxxxxxxx
  enabled_eventhub_namespace: xxxxxxxxxxxxxxx
  enabled_mssqldb: xxxxxxxxxxxxxxx
  enabled_mssqlsrv: xxxxxxxxxxxxxxx
  enabled_redis: xxxxxxxxxxxxxxx
  enabled_servicebus: xxxxxxxxxxxxxxx
  environment: xxxxxxxxxxxxxxx
  eventhub_capacity: xxxxxxxxxxxxxxx
  eventhub_maximum_throughput_units: xxxxxxxxxxxxxxx
  location: xxxxxxxxxxxxxxx
  logs_daily_quota_gb: xxxxxxxxxxxxxxx
  logs_retention_in_days: xxxxxxxxxxxxxxx
  mssqldb_auto_pause_delay_in_minutes: xxxxxxxxxxxxxxx
  mssqldb_long_term_retention_policy_enabled: xxxxxxxxxxxxxxx
  mssqldb_max_size_gb: xxxxxxxxxxxxxxx
  mssqldb_min_capacity: xxxxxxxxxxxxxxx
  mssqldb_sku_name: xxxxxxxxxxxxxxx
  mssqldb_storage_account_type: xxxxxxxxxxxxxxx
  mssqlsrv_admin_gp_login_username: xxxxxxxxxxxxxxx
  mssqlsrv_admin_group_object_ids: xxxxxxxxxxxxxxx
  mssqlsrv_retention_days: xxxxxxxxxxxxxxx
  project: xxxxxxxxxxxxxxx
  redis_capacity: xxxxxxxxxxxxxxx
  redis_family: xxxxxxxxxxxxxxx
  redis_sku_name: xxxxxxxxxxxxxxx
  reports_email: xxxxxxxxxxxxxxx
  rg_vnet_name: xxxxxxxxxxxxxxx
  terraform_remote-state_strgacc_name: xxxxxxxxxxxxxxx
  vmImage: xxxxxxxxxxxxxxx
  vnet_name: xxxxxxxxxxxxxxx
