apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: carregar-yaml
  title: Carregar valores de YAML
spec:
  owner: group:default/devops
  type: service

  parameters:
    - title: Dados do YAML
      required: [url]
      properties:
        url:
          type: string
          description: URL do arquivo YAML

  steps:
    - id: fetch
      name: Buscar YAML
      action: caixa:get-values-from-url
      input:
        url: ${{ parameters.url }}

    - id: log
      name: Mostrar variáveis
      action: debug:log
      input:
        message: |
          YAML carregado com sucesso:
          ${{ steps.fetch.output.variables }}
